// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGCSgP-oV5Os83m-YB7OJ45vEwEv103E',
    appId: '1:780525835293:web:cac24b60f6845d87bd62f4',
    messagingSenderId: '780525835293',
    projectId: 'auction-42108',
    authDomain: 'auction-42108.firebaseapp.com',
    storageBucket: 'auction-42108.firebasestorage.app',
    measurementId: 'G-D0JPLNE8SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQg7bzkHdoTT9aB6ZJVrMi9IJOJJ2_6Cg',
    appId: '1:780525835293:android:bf235c5461f5f62abd62f4',
    messagingSenderId: '780525835293',
    projectId: 'auction-42108',
    storageBucket: 'auction-42108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_MBk4L9JglT25N8TBT2-wX3AyydEqEYQ',
    appId: '1:780525835293:ios:8baaeb8134c0b330bd62f4',
    messagingSenderId: '780525835293',
    projectId: 'auction-42108',
    storageBucket: 'auction-42108.firebasestorage.app',
    iosBundleId: 'com.jr.Auctions',
  );
}
